name: stamp
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.3.11=h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy=1.24.3=py39h14f4228_0
  - numpy-base=1.24.3=py39h31eccc5_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1w=h7f8727e_0
  - pillow=10.3.0=py39h5eee18b_0
  - pip=24.0=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - pytorch=1.10.2=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.10.2=py39_cu113
  - torchvision=0.11.3=py39_cu113
  - typing_extensions=4.11.0=py39h06a4308_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
    - anndata==0.10.7
    - array-api-compat==1.7.1
    - asttokens==2.4.1
    - comm==0.2.2
    - contourpy==1.2.1
    - cycler==0.12.1
    - dcor==0.6
    - debugpy==1.8.1
    - decorator==5.1.1
    - exceptiongroup==1.2.1
    - executing==2.0.1
    - fonttools==4.53.0
    - get-annotations==0.1.2
    - h5py==3.11.0
    - importlib-metadata==7.2.0
    - importlib-resources==6.4.0
    - ipykernel==6.29.4
    - ipython==8.18.1
    - jedi==0.19.1
    - joblib==1.4.2
    - jupyter-client==8.6.2
    - jupyter-core==5.7.2
    - kiwisolver==1.4.5
    - legacy-api-wrap==1.4
    - llvmlite==0.42.0
    - matplotlib==3.9.0
    - matplotlib-inline==0.1.7
    - natsort==8.4.0
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - numba==0.59.1
    - packaging==24.1
    - pandas==2.2.2
    - parso==0.8.4
    - patsy==0.5.6
    - pexpect==4.9.0
    - platformdirs==4.2.2
    - prompt-toolkit==3.0.47
    - psutil==6.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.18.0
    - pynndescent==0.5.12
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pyyaml==6.0.2rc1
    - pyzmq==26.0.3
    - scanpy==1.10.1
    - scikit-learn==1.5.0
    - scipy==1.13.1
    - seaborn==0.13.2
    - session-info==1.0.0
    - stack-data==0.6.3
    - stamp==0.1.0
    - statsmodels==0.14.2
    - stdlib-list==0.10.0
    - threadpoolctl==3.5.0
    - tornado==6.4.1
    - tqdm==4.66.4
    - traitlets==5.14.3
    - tzdata==2024.1
    - umap-learn==0.5.6
    - wcwidth==0.2.13
    - zipp==3.19.2
prefix: /home/gaoyicheng/anaconda3/envs/stamp
